### ISSUE TITLE
bootstrap problem with spork

### ISSUE THREAD

**Issue by RaimundSchramm** [sporkrb/spork-rails#1]
Hi Tim,

I'm using ruby 1.9.2-p290 (+ rvm + gemset) and rails 3.1.3 (+ bundler) for this app (created for rspec so no test folder is present) on Ubuntu 10.04 .

I just tried to install my development-and-test-gem-group containing
- guard-rspec (installs 0.6.0 + guard 1.0.0 as dependency),
- spork-rails (installs 3.2.0 + spork 1.0.0rc0 as dependency) and
- rspec-rails (installs rspec-rails 2.8.1 + rspec 2.8 as dependency)

When i now try to bootstrap my spec_helper.rb file as stated in the documentation (either with or without bundle exec) i get the following error message in my terminal:

bla@bla:~/Aptana Studio 3 Workspace/appname$ bundle exec spork rspec --bootstrap

Using RSpec, Rails
Bootstrapping /bla/Aptana Studio 3 Workspace/appname/spec/spec_helper.rb.

No such file or directory - /path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/lib/spork/../../assets/bootstrap.rb (Errno::ENOENT)

/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in `read'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in`bootstrap'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/lib/spork/runner.rb:64:in `run'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/lib/spork/runner.rb:10:in`run'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/gems/spork-1.0.0rc0/bin/spork:10:in `<top (required)>'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/bin/spork:19:in`load'
/path_to_rvm/.rvm/gems/ruby-1.9.2-p290@gemset_name/bin/spork:19:in `<main>'

Sorry, if this is not the fault of your gem but i have no clue. Maybe you can give me a hint if i did install or configure wrongly.

Thanks in advance
Raimund

**Comment by readeharris** [comment]
I am experiencing the same issue, running 1.9.2-p290 on Rails 3.2.0 with rvm and a gemset. `bundle exec spork rspec --bootstrap` results in:

`Using RSpec, Rails
Bootstrapping /Users/Reade/Sites/c2a/spec/spec_helper.rb.
No such file or directory - /Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/lib/spork/../../assets/bootstrap.rb (Errno::ENOENT)
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in 'read'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/lib/spork/test_framework.rb:99:in 'bootstrap'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/lib/spork/runner.rb:64:in 'run'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/lib/spork/runner.rb:10:in 'run'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/gems/spork-1.0.0rc0/bin/spork:10:in '<top (required)>'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/bin/spork:19:in 'load'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@c2a_revamp/bin/spork:19:in '<main>`

Thanks for working on the gem, Tim!

**Comment by macarthy** [comment]
Same issue here as readeharris

Running 1.9.2-p290 on Rails 3.2.0 with rvm and a gemset on OSX

Also maybe you should mention the need to use `bunde exec` when running --bootstrap
 `bundle exec spork rspec --bootstrap`

**Comment by brutuscat** [comment]
Same here using ruby-1.9.3-p0 and rvm. Executing like this:

```
bundle exec spork rspec --bootstrap
```

**Comment by macarthy** [comment]
This is actually an issue in spork, there is a patch summited to fix it. 
Basically the bootstrap file was not included in the Gemspec. 

https://github.com/sporkrb/spork/pull/169

AFAIK You can actually just copy the bootstrap contents in your helper files

**Comment by readeharris** [comment]
I can confirm that this works fine by requiring `spork` and manually adding the `Spork.prefork` and `Spork.each_run` blocks to your test helper file.

**Comment by RaimundSchramm** [comment]
Me too, thanks for the hint macarthy.

**Comment by blindninja** [comment]
I'm having the same problem running on OS X Lion with RVM 1.9.3-p0 and spork 1.0.0rc0.  

```
No such file or directory - /Users/peter/.rvm/gems/ruby-1.9.3-p0@webtools/gems/spork-1.0.0rc0/lib/spork/../../assets/bootstrap.rb (Errno::ENOENT)
```

**Comment by timcharper** [comment]
Fixed with https://github.com/sporkrb/spork/commit/6e6b5b6dba89c386828b416f8893c7d0449c4f64, is in release spork-rails rc2
